### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by armangiter** [mahdipanahimpui/shorre_task#1]
```
Traceback (most recent call last):
  File "/home/fteam6/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/fteam6/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fteam6/projects/shorre_task/app.py", line 36, in background_thread
    for shorre_value, frame_num in detect_track_video(input_path, weights_path, show_video=True, output_name=output_video):
  File "/home/fteam6/projects/shorre_task/track_detect.py", line 57, in detect_track_video
    tracker = cv2.TrackerCSRT_create()
AttributeError: module 'cv2' has no attribute 'TrackerCSRT_create'

```

**Comment by mahdipanahimpui** [comment]
use 
pip install opencv-python==4.7.0.72
